### ISSUE TITLE
Training an object detection network without flip and rotation the images

### ISSUE THREAD

**Issue by celalutku** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#1]
Hello,

Is it possible to train a object detection network without flipping and rotation the training images. Actually, I want to read some numbers but I don't want that the model to detect a 6 as 9 upside down. I know it is easier to use an image classification model for this purpose but just want to use an object detection network.

I hope there is an easy way.

Thanks

**Comment by armaanpriyadarshan** [comment]
Hmmm... I am not sure. Let me know if you find any solutions so others might learn and we can close the issue

**Comment by armaanpriyadarshan** [comment]
It's been 15 days, so I'll close the issue. If any errors or new findings resurface I will reopen it.
