### ISSUE TITLE
Installation issue: apache-beam avro-python3 incompatibility

### ISSUE THREAD

**Issue by AnAnalogGuy** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#2]
During installation, at this step:

_copy object_detection\packages\tf2\setup.py .
python -m pip install ._

the following error is reported on the console:

_apache-beam 2.23.0 requires avro-python3!=1.9.2,<1.10.0,>=1.8.1; python_version >= "3.0", but you'll have avro-python3 1.10.0 which is incompatible.

tensorflow-metadata 0.23.0 requires absl-py<0.9,>=0.7, but you'll have absl-py 0.10.0 which is incompatible._

I guess it's not related to this project's code and i'm not sure if it has an effect on this application at all. Would be nice to clarify if there actually is a related dependency in the code or if this error can be ignored.

**Comment by armaanpriyadarshan** [comment]
Hi! This shouldn't have much of an impact on the code. You should try to proceed, if you do face any issues, just change the package version by issuing
 
``` pip install absl-py==0.8```

and

```pip install avro-python3==1.8.1```

or whatever versions you need

**Comment by AnAnalogGuy** [comment]
After having successfully completed the example, I can confirm the incompatibility error above has no impact.

**Comment by armaanpriyadarshan** [comment]
Great!
