### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by Solongo1234** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#4]
main_model_tf2  I am getting this error. How to fix it? Pls help
![image](https://user-images.githubusercontent.com/70737854/92198719-b0b7b500-eea7-11ea-95ce-ab6ac7fab0d9.png)

**Comment by armaanpriyadarshan** [comment]
How much memory do you have on your system? If you don't have enough you might have to reduce the batch_size further in the pipeline.config file.
