### ISSUE TITLE
Hi can you help me? to fix the problem with "pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI"

### ISSUE THREAD

**Issue by hyunkon** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#7]
I already followed your "Training-a-Custom-TensorFlow-2.X-Object-Detector" weeks ago and could make it work before. recently I had some problem with my Laptop and had to start from the scratch after I reinstall my Windows 10.  during following your instructions,  
after installing Visual C++ 2015 build tools by visualcppbuildtools_full
I had so many red lines with 
pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

(tensorflow) C:\Users\h_k_k>pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\h_k_k\appdata\local\temp\pip-req-build-nef0y958
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\h_k_k\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\h_k_k\AppData\Local\Temp\pip-wheel-zlgkoyfk'
       cwd: C:\Users\h_k_k\AppData\Local\Temp\pip-req-build-nef0y958\PythonAPI
  Complete output (32 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\pycocotools
  creating build\temp.win-amd64-3.8\common
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include -I../common -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
  _mask.c
  c:\users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  pycocotools/_mask.c(3334): warning C4244: '=': conversion from 'Py_ssize_t' to 'siz', possible loss of data
  pycocotools/_mask.c(3744): warning C4244: 'function': conversion from 'npy_intp' to 'siz', possible loss of data
  pycocotools/_mask.c(6751): warning C4244: '=': conversion from 'npy_intp' to 'siz', possible loss of data
  pycocotools/_mask.c(7509): warning C4244: '=': conversion from 'Py_ssize_t' to 'siz', possible loss of data
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include -I../common -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
  maskApi.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\h_k_k\anaconda3\envs\tensorflow\libs /LIBPATH:C:\Users\h_k_k\anaconda3\envs\tensorflow\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit__mask build\temp.win-amd64-3.8\Release\pycocotools/_mask.obj build\temp.win-amd64-3.8\Release\../common/maskApi.obj /OUT:build\lib.win-amd64-3.8\pycocotools\_mask.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\pycocotools\_mask.cp38-win_amd64.lib
  _mask.obj : warning LNK4197: export 'PyInit__mask' specified multiple times; using first specification
     Creating library build\temp.win-amd64-3.8\Release\pycocotools\_mask.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\pycocotools\_mask.cp38-win_amd64.exp
  Generating code
  Finished generating code
  LINK : fatal error LNK1158: cannot run 'rc.exe'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\h_k_k\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\h_k_k\AppData\Local\Temp\pip-req-build-nef0y958
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\h_k_k\AppData\Local\Temp\pip-req-build-nef0y958\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "C:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
      module_list, module_metadata = create_extension_list(
    File "C:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "C:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
DEPRECATION: Could not build wheels for pycocotools which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\h_k_k\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\h_k_k\AppData\Local\Temp\pip-record-9vbxqta6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\h_k_k\anaconda3\envs\tensorflow\Include\pycocotools'
         cwd: C:\Users\h_k_k\AppData\Local\Temp\pip-req-build-nef0y958\PythonAPI
    Complete output (21 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include -I../common -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
    _mask.c
    c:\users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    pycocotools/_mask.c(3334): warning C4244: '=': conversion from 'Py_ssize_t' to 'siz', possible loss of data
    pycocotools/_mask.c(3744): warning C4244: 'function': conversion from 'npy_intp' to 'siz', possible loss of data
    pycocotools/_mask.c(6751): warning C4244: '=': conversion from 'npy_intp' to 'siz', possible loss of data
    pycocotools/_mask.c(7509): warning C4244: '=': conversion from 'Py_ssize_t' to 'siz', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\h_k_k\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\include -I../common -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include -IC:\Users\h_k_k\anaconda3\envs\tensorflow\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
    maskApi.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\h_k_k\anaconda3\envs\tensorflow\libs /LIBPATH:C:\Users\h_k_k\anaconda3\envs\tensorflow\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit__mask build\temp.win-amd64-3.8\Release\pycocotools/_mask.obj build\temp.win-amd64-3.8\Release\../common/maskApi.obj /OUT:build\lib.win-amd64-3.8\pycocotools\_mask.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\pycocotools\_mask.cp38-win_amd64.lib
    _mask.obj : warning LNK4197: export 'PyInit__mask' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.8\Release\pycocotools\_mask.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\pycocotools\_mask.cp38-win_amd64.exp
    Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\h_k_k\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\h_k_k\\AppData\\Local\\Temp\\pip-req-build-nef0y958\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\h_k_k\AppData\Local\Temp\pip-record-9vbxqta6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\h_k_k\anaconda3\envs\tensorflow\Include\pycocotools' Check the logs for full command output.

Any helps or comments? ;)

**Comment by armaanpriyadarshan** [comment]
Just to make sure, you do have Visual Studio 2015 on your PATH? Did TensorFlow import successfully? And finally do you have a working version of NumPy?

**Comment by hyunkon** [comment]
Hey~~
today I found that I did not install numpy and could have the correct result after I install it!!   I think you may write numpy installation on your presentation and it will prevent the problem I face.  Anyway Thanks a lot for your kind and wise help!!! 

hope you have a great weekend!!!

**Comment by armaanpriyadarshan** [comment]
Ok, that's great! I'll close the issue, but if any issues resurface feel free to let me know.
