### ISSUE TITLE
Tensorflow GPU tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

### ISSUE THREAD

**Issue by sabrisangjaya** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#8]
My setting is same Python 3.7, CUDA 10.1, cudnn 7.6.5. i try to use GPU but i got error
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse
same as https://github.com/tensorflow/tensorflow/issues/38518 , so i must disable gpu to run your code

**Comment by armaanpriyadarshan** [comment]
When did this error occur? Were you able to import TensorFlow? You should try reducing batch_size to 2, or 1 if that doesn't work. And I'd recommend upgrading your Python to 3.8.

**Comment by sabrisangjaya** [comment]
when running python object_detection\builders\model_builder_tf2_test.py and when do training process

**Comment by sabrisangjaya** [comment]
Solved upgrade python to 3.7.9,  downgrade tensorflow to 2.2.0, tensorflow-gpu 2.2.0

**Comment by armaanpriyadarshan** [comment]
That's great, let me know if any errors resurface
