### ISSUE TITLE
Error in testing model when running TF-image-od.py

### ISSUE THREAD

**Issue by abdulmanan275** [armaanpriyadarshan/Training-a-Custom-TensorFlow-2.X-Object-Detector#9]
I'm facing this issue when running TF-image-od.py for testing my model. The error is the same as that stated on readme of this repo.
I'm using google colab. When I run the following command
`!python TF-image-od.py `
I get this error.
`Loading model...Done! Took 13.8348548412323 seconds
Running inference for images/test/test.jpg... Done
Traceback (most recent call last):
  File "TF-image-od.py", line 136, in <module>
    cv2.imshow('Object Detector', image_with_detections)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-svkjd8wa/opencv/modules/highgui/src/window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
`
I've installed opencv-python using pip and then rerun the program but still get the same error.

**Comment by mahamatnoumai** [comment]
@abdulmanan275 is opencv installed? if Yes pls check the path nd setup correctly. then it may work for u. 

> The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage' 
`read the messages correctly`

**Comment by armaanpriyadarshan** [comment]
Yes, @mahamatnoumai I believe that's the issue, Make sure you have installed opencv with pip install opencv-python.
